#!/bin/bash

if [ -n "$1" ]
then
    # Let's assume it's Github's username
    mkdir -p $HOME/.ssh
    curl -sSL https://github.com/$1.keys >> $HOME/.ssh/authorized_keys
else
    echo "Please provide a Github.com user name"
fi

